import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import multer from 'multer'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  examHistoryGet,
  examHistoryPost,
  parseSessionKey,
} from '../lib/exam-history-api.mjs'
import {
  documentsGet,
  documentsPost,
  documentsDelete,
} from '../lib/document-api.mjs'
import {
  isAllowedUpload,
  mimeForFileSearch,
  runFileSearchUpload,
  runGenerateExam,
} from '../lib/mock-api.mjs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const UPLOAD_DIR = path.join(__dirname, '..', 'uploads')

if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR, { recursive: true })
}

const ai = null

const upload = multer({
  dest: UPLOAD_DIR,
  limits: { fileSize: 100 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    if (isAllowedUpload(file)) {
      cb(null, true)
      return
    }
    cb(
      new Error(
        `Unsupported file type (${file.mimetype}). Use PDF, TXT, MD, JSON, CSV, or DOCX.`,
      ),
    )
  },
})

const uploadSource = upload.fields([
  { name: 'document', maxCount: 1 },
  { name: 'pdf', maxCount: 1 },
])

const app = express()
app.use(cors())
app.use(express.json({ limit: '2mb' }))

app.post('/api/upload', uploadSource, async (req, res) => {
  const f =
    req.files?.document?.[0] || req.files?.pdf?.[0] || req.file || null
  if (!f) {
    res.status(400).json({
      error:
        'No file uploaded. Use form field "document" (or legacy "pdf") with one file.',
    })
    return
  }

  const filePath = f.path
  const displayName = (f.originalname || 'source').replace(
    /[^\w.\- ]+/g,
    '_',
  ).slice(0, 120)
  const storeMime = mimeForFileSearch(f)

  try {
    const out = await runFileSearchUpload(ai, {
      filePath,
      displayName,
      storeMime,
    })
    res.json(out)
  } catch (e) {
    console.error(e)
    res.status(500).json({ error: e.message || 'Upload failed' })
  } finally {
    try {
      fs.unlinkSync(filePath)
    } catch {
      /* ignore */
    }
  }
})

app.post('/api/generate-exam', async (req, res) => {
  const { fileSearchStoreName, questionCount } = req.body || {}
  const n = Number(questionCount)
  if (!fileSearchStoreName || typeof fileSearchStoreName !== 'string') {
    res.status(400).json({ error: 'fileSearchStoreName is required' })
    return
  }
  if (!Number.isFinite(n) || n < 1 || n > 500) {
    res.status(400).json({ error: 'questionCount must be between 1 and 500' })
    return
  }

  try {
    const out = await runGenerateExam(ai, {
      fileSearchStoreName,
      questionCount: n,
    })
    res.json(out)
  } catch (e) {
    console.error(e)
    const code = e.statusCode || 500
    res.status(code).json({ error: e.message || 'Exam generation failed' })
  }
})

app.get('/api/exam-history', async (req, res) => {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({
      error:
        'Missing or invalid X-Session-Key header (must be a UUID generated by the app)',
    })
    return
  }
  const out = await examHistoryGet(sessionKey)
  res.status(out.status).json(out.body)
})

app.get('/api/documents', async (req, res) => {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({ error: 'Missing or invalid X-Session-Key header' })
    return
  }
  const out = await documentsGet(sessionKey)
  res.status(out.status).json(out.body)
})

app.post('/api/documents', async (req, res) => {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({ error: 'Missing or invalid X-Session-Key header' })
    return
  }
  const out = await documentsPost(sessionKey, req.body || {})
  res.status(out.status).json(out.body)
})

app.delete('/api/documents', async (req, res) => {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({ error: 'Missing or invalid X-Session-Key header' })
    return
  }
  const id = req.query.id
  const out = await documentsDelete(sessionKey, id)
  res.status(out.status).json(out.body)
})

app.post('/api/exam-history', async (req, res) => {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({
      error:
        'Missing or invalid X-Session-Key header (must be a UUID generated by the app)',
    })
    return
  }
  const out = await examHistoryPost(sessionKey, req.body || {})
  res.status(out.status).json(out.body)
})

const PORT = Number(process.env.PORT) || 8787
app.listen(PORT, '127.0.0.1', () => {
  console.log(`API server http://127.0.0.1:${PORT}`)
})
