import {
  examHistoryGet,
  examHistoryPost,
  parseSessionKey,
} from '../lib/exam-history-api.mjs'

async function readJsonBody(req) {
  const chunks = []
  for await (const chunk of req) {
    chunks.push(chunk)
  }
  const raw = Buffer.concat(chunks).toString('utf8')
  if (!raw) return {}
  try {
    return JSON.parse(raw)
  } catch {
    throw new Error('Invalid JSON body')
  }
}

export default async function handler(req, res) {
  const sessionKey = parseSessionKey(req)
  if (!sessionKey) {
    res.status(400).json({
      error:
        'Missing or invalid X-Session-Key header (must be a UUID generated by the app)',
    })
    return
  }

  if (req.method === 'GET') {
    const out = await examHistoryGet(sessionKey)
    res.status(out.status).json(out.body)
    return
  }

  if (req.method === 'POST') {
    let body
    try {
      body = await readJsonBody(req)
    } catch (e) {
      res.status(400).json({ error: e.message })
      return
    }
    const out = await examHistoryPost(sessionKey, body)
    res.status(out.status).json(out.body)
    return
  }

  res.status(405).json({ error: 'Method not allowed' })
}
